apiVersion: v1
kind: Pod
metadata:
  name: monitor-data
spec:
  containers:
    - name: monitor-data
      image: docker.io/kovaleskilab/ml_basic:v3     
      stdin: True
      tty: True
      resources:
        limits:
          memory: 4G
          cpu: 2
        requests:
          memory: 4G
          cpu: 2
      volumeMounts:
        - name: preprocessed-data 
          mountPath: /develop/results
          
  volumes:
    - name: preprocessed-data
      persistentVolumeClaim:
        claimName: preprocessed-data

  restartPolicy: Never
