apiVersion: v1
kind: Pod
metadata:
  name: jupyter-results
spec:
  containers:
    - name: jupyter-results
      image: jupyter/scipy-notebook
      ports:
        - containerPort: 8888
      command: 
        - "bash"
        - "-c"
        - |
          sudo apt-get update && \
          sudo apt-get install -y poppler-utils && \
          pip install pdf2image && \
          start-notebook.sh --NotebookApp.token='' --NotebookApp.password=''
      resources:
        limits:
          memory: 20G
          cpu: 2
        requests:
          memory: 10G
          cpu: 2
      volumeMounts:
        - name: training-results 
          mountPath: /develop/results
      securityContext:
        runAsUser: 0  # Run as root
        allowPrivilegeEscalation: true
          
  volumes:
    - name: training-results
      persistentVolumeClaim:
        claimName: training-results

  restartPolicy: Never