apiVersion: v1
kind: Pod
metadata:
  name: monitor-results
spec:
  containers:
    - name: monitor-results
      image: docker.io/kovaleskilab/ml_basic:v4  
      stdin: True
      tty: True
      resources:
        limits:
          memory: 20G
          cpu: 2
        requests:
          memory: 10G
          cpu: 2
      volumeMounts:
        - name: training-results 
          mountPath: /develop/results
          
  volumes:
    - name: training-results
      persistentVolumeClaim:
        claimName: training-results

  restartPolicy: Never