apiVersion: v1
kind: Pod
metadata:
  name: ethan-monitor-volumes
spec:
  containers:
    - name: monitor-volumes
      image: docker.io/kovaleskilab/ml_basic:v4  
      stdin: True
      tty: True
      resources:
        limits:
          memory: 20G
          cpu: 2
        requests:
          memory: 20G
          cpu: 2
      volumeMounts:
        - name: dft-volumes
          mountPath: /develop/data
          
  volumes:
    - name: dft-volumes
      persistentVolumeClaim:
        claimName: dft-volumes

  restartPolicy: Never
