apiVersion: v1
kind: Pod
metadata:
  name: ethan-monitor-data
spec:
  containers:
    - name: monitor-data
      image: docker.io/kovaleskilab/ml_basic:v4  
      stdin: True
      tty: True
      resources:
        limits:
          memory: 20G
          cpu: 2
        requests:
          memory: 20G
          cpu: 2
      volumeMounts:
        - name: preprocessed-data 
          mountPath: /develop/data/preprocessed_data
          
  volumes:
    - name: preprocessed-data
      persistentVolumeClaim:
        claimName: preprocessed-data

  restartPolicy: Never
