apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfe-data
  namespace: gpn-mizzou-muem
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 250Gi
  storageClassName: standard
