apiVersion: batch/v1
kind: Job 
metadata:
  name: ethan-data-job
  namespace: gpn-mizzou-muem 
spec:
  ttlSecondsAfterFinished: 3600
  completions: 1
  backoffLimit: 0
  template:
    metadata:
      name: ethan-data-job
      namespace: gpn-mizzou-muem
    spec:
      restartPolicy: Never
      containers:
        - name: ethan-data-job
          image: docker.io/kovaleskilab/ml_basic:v4-kube
          imagePullPolicy: Always
          env:
            - name: PYTHONUNBUFFERED
              value: "1"
          command: ["/bin/sh", "-c"]

          args: ["set -x &&
        mkdir -p /root/.ssh &&
                    pip install seaborn &&
                    git clone git@github.com:Kovaleski-Research-Lab/near_field_emulator.git && 
                    python3 /develop/code/near_field_emulator/main.py --config /develop/code/near_field_emulator/conf/config.yaml && sleep 3600"]
          resources:
            limits:
              memory: 200Gi
              cpu: 32
            requests:
              memory: 200Gi
              cpu: 32
          volumeMounts: 
            - name: refidx-data
              mountPath: /develop/data/preprocessed_data
            - name: dft-volumes-refidx
              mountPath: /develop/results
            - name: ssh-key
              mountPath: "/root/.ssh"
              readOnly: true

      volumes:
        - name: refidx-data  # this is where preprocessed pickle files are
          persistentVolumeClaim:
            claimName: refidx-data
        - name: dft-volumes-refidx
          persistentVolumeClaim:
            claimName: dft-volumes-refidx
        - name: ssh-key
          secret:
            secretName: github-ssh-key
            defaultMode: 0400