apiVersion: batch/v1
kind: Job
metadata:
  name: ethan-nfe-ml
spec:
  backoffLimit: 0
  template:
    metadata:
      name: ethan-nfe-ml
    spec:
      restartPolicy: Never
      containers:
      - name: ethan-nfe-ml
        image: docker.io/kovaleskilab/ml_ssh:latest
        imagePullPolicy: Always
        command: ["/bin/sh", "-c"]
        args: ["git clone https://github.com/Kovaleski-Research-Lab/near_field_emulator.git && /usr/sbin/sshd -D"]
        resources:
          limits:
            memory: 300Gi
            cpu: 24
            nvidia.com/a100: 1
          requests:
            memory: 300Gi
            cpu: 24
            nvidia.com/a100: 1
        volumeMounts:
        - name: refidx-data
          mountPath: /develop/data
        - name: refidx-data
          mountPath: /develop/results
        - name: shm 
          mountPath: /dev/shm
      volumes:
      - name: refidx-data
        persistentVolumeClaim:
          claimName: refidx-data
      - name: shm
        emptyDir:
          medium: Memory