apiVersion: batch/v1
kind: Job 
metadata:
  name: compile_data
  namespace: gpn-mizzou-muem 
spec:
  completions: 1
  backoffLimit: 0
  template:
    metadata:
      name: compile_data
      namespace: gpn-mizzou-muem
    spec:
      restartPolicy: Never
      containers:
        - name: compile_data
          image: docker.io/kovaleskilab/ml_basic:v4
          command: ["/bin/sh", "-c"]

          args: ["git clone https://github.com/Kovaleski-Research-Lab/near_field_inverse_design.git; 
                python3 /develop/code/near_field_inverse_design/run.py --config /develop/code/near_field_inverse_design/config.yaml"]
          resources:
            limits:
              memory: 150Gi
              cpu: 4
            requests:
              memory: 100Gi
              cpu: 4
          volumeMounts: 
            - name: preprocessed-data
              mountPath: /develop/data/preprocessed_data

      volumes:
        - name: preprocessed-data  # this is where preprocessed pickle files are
          persistentVolumeClaim:
            claimName: preprocessed-data