apiVersion: batch/v1
kind: Job
metadata:
  name: convlstm-evaluation 
spec:
  ttlSecondsAfterFinished: 3600
  template:
    spec:
      restartPolicy: Never 
      containers:
        - name: convlstm-evaluation
          image: docker.io/kovaleskilab/ml_basic:v4 
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8880
          env:
            - name: NCCL_SOCKET_IFNAME
              value: eth0
            - name: NCCL_DEBUG
              value: INFO
          command: ["/bin/sh", "-c"]
          args: ["set -x &&
                  mkdir -p /root/.ssh &&
                  git clone git@github.com:Kovaleski-Research-Lab/near_field_inverse_design.git &&
                  python3 /develop/code/near_field_inverse_design/main.py --config /develop/code/near_field_inverse_design/config.yaml"]
          resources:
            limits:
              memory: 144Gi 
              cpu: 16 
              nvidia.com/a100: 1
            requests:
              memory: 144Gi
              cpu: 16
              nvidia.com/a100: 1
          volumeMounts:
            - name: training-results
              mountPath: /develop/results
            - name: shm 
              mountPath: /dev/shm
            - name: ssh-key
              mountPath: "/root/.ssh"
              readOnly: true

      volumes:
        - name: training-results
          persistentVolumeClaim:
            claimName: training-results
        - name: shm
          emptyDir:
            medium: Memory
        - name: ssh-key
          secret:
            secretName: github-ssh-key
            defaultMode: 0400