apiVersion: batch/v1
kind: Job 
metadata:
  name: ethan-data-job
  namespace: gpn-mizzou-muem 
spec:
  ttlSecondsAfterFinished: 3600
  completions: 1
  backoffLimit: 0
  template:
    metadata:
      name: ethan-data-job
      namespace: gpn-mizzou-muem
    spec:
      restartPolicy: Never
      containers:
        - name: ethan-data-job
          image: docker.io/kovaleskilab/ml_basic:v4
          command: ["/bin/sh", "-c"]

          args: ["set -x &&
        mkdir -p /root/.ssh &&
                    git clone git@github.com:Kovaleski-Research-Lab/near_field_emulator.git && 
                    python3 /develop/code/near_field_emulator/main.py --config /develop/code/near_field_emulator/config.yaml"]
          resources:
            limits:
              memory: 64Gi
              cpu: 20
            requests:
              memory: 64Gi
              cpu: 20
          volumeMounts: 
            - name: preprocessed-data
              mountPath: /develop/data/preprocessed_data
            - name: ssh-key
              mountPath: "/root/.ssh"
              readOnly: true

      volumes:
        - name: preprocessed-data  # this is where preprocessed pickle files are
          persistentVolumeClaim:
            claimName: preprocessed-data
        - name: ssh-key
          secret:
            secretName: github-ssh-key
            defaultMode: 0400