apiVersion: v1
kind: Pod
metadata:
  name: save-eval-plots
spec:
  containers:
    - name: save-eval-plots
      image: jupyter/scipy-notebook
      ports:
        - containerPort: 8888
      command: 
        - "bash"
        - "-c"
        - |
          sudo apt-get update && \
          sudo apt-get install -y poppler-utils && \
          pip install pdf2image pyyaml && \
          python3 /develop/code/near_field_inverse_design/kube/save_eval_plots.py
      resources:
        limits:
          memory: 20G
          cpu: 2
        requests:
          memory: 10G
          cpu: 2
      volumeMounts:
        - name: training-results 
          mountPath: /develop/results
        - name: saved-results
          mountPath: /develop/saved_results
      securityContext:
        runAsUser: 0  # Run as root
        allowPrivilegeEscalation: true
          
  volumes:
    - name: training-results
      persistentVolumeClaim:
        claimName: training-results
    - name: saved-results
      emptyDir: {}

  restartPolicy: Never