apiVersion: batch/v1
kind: Job
metadata:
  name: save-eval-plots
spec:
  ttlSecondsAfterFinished: 3600
  template:
    spec:
      restartPolicy: Never 
      containers:
        - name: save-eval-plots
          image: docker.io/kovaleskilab/ml_basic:v4 
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8880
          env:
            - name: NCCL_SOCKET_IFNAME
              value: eth0
            - name: NCCL_DEBUG
              value: INFO
          command: ["/bin/sh", "-c"]
          args: ["set -x &&
                  mkdir -p /root/.ssh &&
                  git clone git@github.com:Kovaleski-Research-Lab/near_field_inverse_design.git &&
                  apt-get update &&
                  apt-get install -y poppler-utils &&
                  pip install pdf2image &&
                  cd &&
                  cd /develop/code/near_field_inverse_design &&
                  python3 -m kube.save_eval_plots &&
                  echo 'Script completed, sleeping for 5 minutes to allow file copy' &&
                  sleep 300"]
          resources:
            limits:
              memory: 10Gi 
              cpu: 2
            requests:
              memory: 10Gi
              cpu: 2
          volumeMounts:
            - name: training-results
              mountPath: /develop/results
            - name: shm 
              mountPath: /dev/shm
            - name: ssh-key
              mountPath: "/root/.ssh"
              readOnly: true

      volumes:
        - name: training-results
          persistentVolumeClaim:
            claimName: training-results
        - name: shm
          emptyDir:
            medium: Memory
        - name: ssh-key
          secret:
            secretName: github-ssh-key
            defaultMode: 0400